groups/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from .views import GroupDetailView, GroupActivityView

urlpatterns = patterns('geonode.groups.views',
                       url(r'^$', TemplateView.as_view(template_name='groups/group_list.html'), name="group_list"),
                       url(r'^create/$', 'group_create', name="group_create"),
                       url(r'^group/(?P<slug>[-\w]+)/$', GroupDetailView.as_view(), name='group_detail'),
                       url(r'^group/(?P<slug>[-\w]+)/update/$', 'group_update', name='group_update'),
                       url(r'^group/(?P<slug>[-\w]+)/members/$', 'group_members', name='group_members'),
                       url(r'^group/(?P<slug>[-\w]+)/invite/$', 'group_invite', name='group_invite'),
                       url(r'^group/(?P<slug>[-\w]+)/members_add/$', 'group_members_add', name='group_members_add'),
                       url(r'^group/(?P<slug>[-\w]+)/member_remove/(?P<username>.+)$', 'group_member_remove',
                           name='group_member_remove'),
                       url(r'^group/(?P<slug>[-\w]+)/remove/$', 'group_remove', name='group_remove'),
                       url(r'^group/(?P<slug>[-\w]+)/join/$', 'group_join', name='group_join'),
                       url(r'^group/[-\w]+/invite/(?P<token>[\w]{40})/$', 'group_invite_response',
                           name='group_invite_response'),
                       url(r'^group/(?P<slug>[-\w]+)/activity/$', GroupActivityView.as_view(), name='group_activity'),
                       )

groups/models.py
import datetime
import hashlib

from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from django.db import models, IntegrityError
from django.utils.translation import ugettext_lazy as _
from django.db.models import signals
from django.contrib.sites.models import Site
from django.template.loader import render_to_string
from django.core.mail import send_mail

from taggit.managers import TaggableManager
from guardian.shortcuts import get_objects_for_group


class GroupProfile(models.Model):
    GROUP_CHOICES = [
        ("public", _("Public")),
        ("public-invite", _("Public (invite-only)")),
        ("private", _("Private")),
    ]

    access_help_text = _('Public: Any registered user can view and join a public group.<br>'
                         'Public (invite-only):Any registered user can view the group.  '
                         'Only invited users can join.<br>'
                         'Private: Registered users cannot see any details about the group, including membership.  '
                         'Only invited users can join.')
    email_help_text = _('Email used to contact one or all group members, '
                        'such as a mailing list, shared email, or exchange group.')

    group = models.OneToOneField(Group)
    title = models.CharField(_('Title'), max_length=50)
    slug = models.SlugField(unique=True)
    logo = models.ImageField(_('Logo'), upload_to="people_group", blank=True)
    description = models.TextField(_('Description'))
    email = models.EmailField(
        _('Email'),
        null=True,
        blank=True,
        help_text=email_help_text)
    keywords = TaggableManager(
        _('Keywords'),
        help_text=_("A space or comma-separated list of keywords"),
        blank=True)
    access = models.CharField(
        _('Access'),
        max_length=15,
        default="public'",
        choices=GROUP_CHOICES,
        help_text=access_help_text)
    last_modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        group, created = Group.objects.get_or_create(name=self.slug)
        self.group = group
        super(GroupProfile, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        Group.objects.filter(name=self.slug).delete()
        super(GroupProfile, self).delete(*args, **kwargs)

    @classmethod
    def groups_for_user(cls, user):
        """
        Returns the groups that user is a member of.  If the user is a superuser, all groups are returned.
        """
        if user.is_authenticated():
            if user.is_superuser:
                return cls.objects.all()
            return cls.objects.filter(groupmember__user=user)
        return []

    def __unicode__(self):
        return self.title

    def keyword_list(self):
        """
        Returns a list of the Group's keywords.
        """
        return [kw.name for kw in self.keywords.all()]

    def resources(self, resource_type=None):
        """
        Returns a generator of objects that this group has permissions on.

        :param resource_type: Filter's the queryset to objects with the same type.
        """

        queryset = get_objects_for_group(
            self.group, [
                'base.view_resourcebase', 'base.change_resourcebase'], any_perm=True)

        if resource_type:
            queryset = [
                item for item in queryset if hasattr(
                    item,
                    resource_type)]

        for resource in queryset:
            yield resource

    def member_queryset(self):
        return self.groupmember_set.all()

    def get_managers(self):
        """
        Returns a queryset of the group's managers.
        """
        return get_user_model().objects.filter(
            id__in=self.member_queryset().filter(
                role='manager').values_list(
                "user",
                flat=True))

    def user_is_member(self, user):
        if not user.is_authenticated():
            return False
        return user.id in self.member_queryset().values_list("user", flat=True)

    def user_is_role(self, user, role):
        if not user.is_authenticated():
            return False
        return self.member_queryset().filter(user=user, role=role).exists()

    def can_view(self, user):
        if self.access == "private":
            return user.is_authenticated() and self.user_is_member(user)
        else:
            return True

    def can_invite(self, user):
        if not user.is_authenticated():
            return False
        return self.user_is_role(user, "manager")

    def join(self, user, **kwargs):
        if user == user.get_anonymous():
            raise ValueError("The invited user cannot be anonymous")
        member, created = GroupMember.objects.get_or_create(group=self, user=user, defaults=kwargs)
        if created:
            user.groups.add(self.group)
        else:
            raise ValueError("The invited user \"{0}\" is already a member".format(user.username))

    def invite(self, user, from_user, role="member", send=True):
        params = dict(role=role, from_user=from_user)
        if isinstance(user, get_user_model()):
            params["user"] = user
            params["email"] = user.email
        else:
            params["email"] = user
        bits = [
            settings.SECRET_KEY,
            params["email"],
            str(datetime.datetime.now()),
            settings.SECRET_KEY
        ]
        params["token"] = hashlib.sha1("".join(bits)).hexdigest()

        # If an invitation already exists, re-use it.
        try:
            invitation = self.invitations.create(**params)
        except IntegrityError:
            invitation = self.invitations.get(
                group=self,
                email=params["email"])

        if send:
            invitation.send(from_user)
        return invitation

    @models.permalink
    def get_absolute_url(self):
        return ('group_detail', (), {'slug': self.slug})

    @property
    def class_name(self):
        return self.__class__.__name__


class GroupMember(models.Model):

    group = models.ForeignKey(GroupProfile)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    role = models.CharField(max_length=10, choices=[
        ("manager", _("Manager")),
        ("member", _("Member")),
    ])
    joined = models.DateTimeField(default=datetime.datetime.now)


class GroupInvitation(models.Model):

    group = models.ForeignKey(GroupProfile, related_name="invitations")
    token = models.CharField(max_length=40)
    email = models.EmailField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="pg_invitations_received")
    from_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="pg_invitations_sent")
    role = models.CharField(max_length=10, choices=[
        ("manager", _("Manager")),
        ("member", _("Member")),
    ])
    state = models.CharField(
        max_length=10,
        choices=(
            ("sent", _("Sent")),
            ("accepted", _("Accepted")),
            ("declined", _("Declined")),
        ),
        default="sent",
    )
    created = models.DateTimeField(default=datetime.datetime.now)

    def __unicode__(self):
        return "%s to %s" % (self.email, self.group.title)

    class Meta:
        unique_together = [("group", "email")]

    def send(self, from_user):

        current_site = Site.objects.get_current()
        domain = unicode(current_site.domain)
        ctx = {
            "invite": self,
            "group": self.group,
            "from_user": from_user,
            "domain": domain,
        }
        subject = render_to_string("groups/email/invite_user_subject.txt", ctx)
        message = render_to_string("groups/email/invite_user.txt", ctx)
        # TODO Send a notification rather than a mail
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email])

    def accept(self, user):
        if not user.is_authenticated() or user == user.get_anonymous():
            raise ValueError("You must log in to accept invitations")
        if not user.email == self.email:
            raise ValueError(
                "You can't accept an invitation that wasn't for you")
        self.group.join(user, role=self.role)
        self.state = "accepted"
        self.user = user
        self.save()

    def decline(self, user):
        if not user.is_authenticated() or user == user.get_anonymous():
            raise ValueError("You must log in to decline invitations")
        if not user.email == self.email:
            raise ValueError(
                "You can't decline an invitation that wasn't for you")
        self.state = "declined"
        self.save()


def group_pre_delete(instance, sender, **kwargs):
    """Make sure that the anonymous group is not deleted"""
    if instance.name == 'anonymous':
        raise Exception('Deletion of the anonymous group is\
         not permitted as will break the geonode permissions system')

signals.pre_delete.connect(group_pre_delete, sender=Group)

groups/templates/groups/_group_list_item.html
{% verbatim %}
<article ng-repeat="group in results" ng-cloak class="ng-cloak">
  <div class="col-xs-12 col-sm-6 col-lg-4 group-container">
    <div class="col-xs-12 group-avatar">
      <div class="col-xs-4 group-image">
        <a ng-if="group.logo" href="{{ group.detail_url }}" ><img ng-if="group.logo" ng-src="{{ group.logo }}" alt="{{ group.title }}" class="group-logo" /></a>
      </div>
      <div class="col-xs-8 group-details">
        <h5><a href="{{ group.detail_url }}">{{ group.title }}</a></h5>
        <!-- <a href="mailto:{{ group.email }}" ng-if="group.email != ''"><i class="fa fa-envelope-o"></i></a> -->
        <p><small>{{ group.description | limitTo: 100 }}{{ group.description.length  > 100 ? '...' : ''}}</small></p>
      </div>
      <div class="col-xs-12 group-items">
        <ul class="list-inline">
          <li>
        <a href="{{ group.detail_url }}">
          <strong>{{ group.member_count }}</strong>
          <ng-pluralize count="group.member_count" when="{'1': 'Member', 'other': 'Members'}"></ng-pluralize>
        </a>
      </li>
      <li>
        <a href="{{ group.detail_url }}">
          <strong>{{ group.manager_count }}</strong>
          <ng-pluralize count="group.manager_count" when="{'1': 'Manager', 'other': 'Managers'}"></ng-pluralize>
        </a>
      </li>
    </div>
  </div>
</article>
{% endverbatim %}

groups/templates/groups/_group_opengraph.html
{% load avatar_tags %}
<meta property="og:title" content="{{ object.title|default:object.slug|truncatechars:70 }}" />
<meta property="og:site_name" content="{{ SITE_NAME }}" />
<meta property="og:url" content="http{% if request.is_secure %}s{% endif %}://{{ SITE_DOMAIN }}{{ object.get_absolute_url }}" />
<meta property="og:description" content="Group {{ object.title|default:object.slug }} on {{ SITE_NAME }}" />
<!-- Need to create thumbnails for group logos since there are size restrictions
<meta name="og:image" content="" />
<meta name="og:image:width" content="200" />
<meta name="og:image:height" content="200" />
-->

groups/templates/groups/_group_twittercard.html
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="{{ TWITTER_SITE }}" />
<!-- Twitter truncates twitter:title to 70 characters. -->
<meta name="twitter:title" content="{{ object.title|default:object.slug|truncatechars:70 }}" />
<!-- Twitter truncates twitter:description at the word to 200 characters. -->
<meta name="twitter:description" content="Group {{ object.title|default:object.slug }} on {{ SITE_NAME }}" />
<!-- Need to create thumbnails for group logos since there are size restrictions
<meta name="twitter:image" content="" />
-->

groups/templates/groups/activity.html
{% extends 'site_base.html' %}
{% load activity_tags social_tags i18n %}

{% block extra_head %}
{{ block.super }}{% endblock %}

{% block title %}{%  trans "Activity Feed for"  %} {{ group.title }}{% endblock %}
{% block content_title %}{%  trans "Activity Feed for"  %} {{ group.title }}{% endblock %}

{% comment %}
{% block navlinks %}
<li><a href="{% url "actstream_object_feed" content_type_id=ctype.pk  object_id=actor.pk %}">RSS</a></li>
<li><a href="{% url "actstream_object_feed_atom" content_type_id=ctype.pk  object_id=actor.pk %}">ATOM</a></li>
{% endblock %}
{% endcomment %}

{% block body_outer %}
<div class="page-header">
  <h2 class="page-title">{%  trans "Activity Feed for"  %} <a href="{% url "group_detail" group.slug %}">{{ group.title }}</a></h2>
</div>

<div class="row">
  <div class="col-md-8">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#all" data-toggle="tab"><i class=""></i>{% trans "All" %}</a></li>
      <li><a href="#layers" data-toggle="tab"><i class="fa fa-square-o rotate-45"></i> {% trans "Layers" %}</a></li>
      <li><a href="#maps" data-toggle="tab"><i class="fa fa-map-marker"></i> {% trans "Maps" %}</a></li>
      <li><a href="#comments" data-toggle="tab"><i class="fa fa-comment-o"></i> {% trans "Comments" %}</a></li>
    </ul>
    <div class="tab-content">
      <article id="all" class="tab-pane active">
        <ul class="no-style-list">
        {% for action in action_list %}
          {% activity_item action %}
          {% empty %}
          <p>{% trans "No actions yet" %}</p>
        {% endfor %}
        </ul>
      </article>
      <article id="layers" class="tab-pane">
        <ul class="no-style-list">
        {% for action in action_list_layers %}
          {% activity_item action %}
          {% empty %}
          <p>{% trans "No actions yet" %}</p>
        {% endfor %}
        </ul>
      </article>
      <article id="maps" class="tab-pane">
        <ul class="no-style-list">
        {% for action in action_list_maps %}
          {% activity_item action %}
          {% empty %}
          <p>{% trans "No actions yet" %}</p>
        {% endfor %}
        </ul>
      </article>
      <article id="comments" class="tab-pane">
        <ul class="no-style-list">
        {% for action in action_list_comments %}
          {% activity_item action %}
          {% empty %}
          <p>{% trans "No actions yet" %}</p>
        {% endfor %}
        </ul>
      </article>
    </div>
  </div>
</div>
{% endblock %}

groups/templates/groups/base.html
{% extends "site_base.html" %}

groups/templates/groups/group_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}groups explore{% endblock %}

{% block body_outer %}
  <!-- {% block subnav %}
  <div class="col-md-12">
    <ul class="nav nav-tabs" id="subnav-tabs">
      <li><a href="{% url "group_list" %}" class="explore">{% trans "Explore Groups" %}</a></li>
      <li><a href="{% url "group_create" %}" class="create">{% trans "Create a Group" %}</a></li>
      {% if group %}
      <li><a href="{% url "group_update" group.slug %}" class="update">{% trans "Update Group" %}</a></li>
      <li><a href="{% url "group_remove" group.slug %}" class="remove">{% trans "Remove Group" %}</a></li>
      {% endif %}
    </ul>
  </div>
  {% endblock subnav %} -->
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

groups/templates/groups/group_create.html
{% extends "groups/group_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block head_title %}{% trans "Create Group" %}{% endblock %}
{% block body_class %}groups create{% endblock %}

{% block body %}
    <div class="block">
      <div class="col-md-10">
        <h2 class="page-title">{% trans "Create a Group" %}</h2>
        {% if errors %}
          <div id="errors">
            {% for error in errors %}
              <div>{{ error }}</div>
            {% endfor %}
          </div>
        {% endif %}
        <div>
        <form class="uniForm" id="form" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            {{ form|as_bootstrap }}
            <div class="form_block">
                <input type="hidden" name="action" value="create" />
                <input type="submit" class="btn btn-primary" value="{% trans 'Create' %}"/>
            </div>
        </fieldset>
    </form>
            </div>
        </div>
    </div>
    
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% load i18n %}

{% block title %}{{ object.title|default:object.slug }} — {{ block.super }}{% endblock %}

{% block head %}
  {% if TWITTER_CARD %}
    {% include "groups/_group_twittercard.html" %}
  {% endif %}
  {% if OPENGRAPH_ENABLED %}
    {% include "groups/_group_opengraph.html" %}
  {% endif %}
  {{ block.super }}
{% endblock %}

{% block body_class %}groups{% endblock %}

{% block body_outer %}
<div class="page-header">
  <h2 class="page-title">{{ object.title|default:object.slug }}</h2>
</div>
<div class="row">
  <div class="col-md-8 group-details">
    <div class="row">
      <div class="col-xs-4 col-md-3 group-logo">
      {% if object.logo %}
        <img src="{{ object.logo.url }}" alt="{{ object.title }}" />
      {% else %}
        <!-- <p>{% trans "This group has not created a logo." %}</p> -->
      {% endif %}
      </div>
      <div class="col-xs-8 col-md-9 group-details">
        <p class="group-desc">{{ object.description }}</p>
        {% if object.keyword_list %}
        <p>
          {% for keyword in object.keyword_list %}
            <span class="label label-default">{{ keyword }}</span>
          {% endfor %}
        </p>
        {% else %}
        {% endif %}
        {% if object.email %}
        <p><i class="fa fa-envelope-o"></i>
          <a href="mailto:{{ object.email }}">{{ object.email }}</a>
        </p>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <ul class="list-group">
      {% if is_manager %}
      <li class="list-group-item"><a href="{% url "group_update" object.slug %}">{% trans "Edit Group Details" %}</a></li>
      <li class="list-group-item"><a href="{% url "group_members" object.slug %}">{% trans "Manage Group Members" %}</a></li>
      <li class="list-group-item"><a href="{% url "group_remove" object.slug %}">{% trans "Delete this Group" %}</a></li>
      {% endif %}
      {% if can_view %}
      <li class="list-group-item"><a href="{% url "group_activity" object.slug %}">{% trans "Group Activities" %}</a></li>
      {% endif %}
      <li class="list-group-item">
        <h4>{% trans "Permissions" %}</h4>
        <p>
          {% blocktrans with object.get_access_display as access %}
            This group is <strong>{{ access }}</strong>.
          {% endblocktrans %}
          {% if object.access == "public" %}
            {% trans "Anyone may join this group." %}
            <form class="uniForm" method="POST" action="{% url "group_join" object.slug %}">
              {% csrf_token %}
              {% if not is_member %}
              <input type="submit" class="btn btn-default btn-md btn-block" value="Join Group" />
              {% endif %}
            </form>
          {% else %} {% if object.access == "public-invite" %}
            {% trans "Anyone may view this group but membership is by invitation only." %}
          {% else %} {% if object.access == "private" %}
            {% trans "Membership is by invitation only." %}
          {% endif %} {% endif %} {% endif %}
        </p>
      </li>
      <li class="list-group-item">
        <h4>{% trans "Managers" %}</h4>
        {% for manager in object.get_managers %}
        {% with manager as profile %}
          {% include "people/_profile_about_item.html" %}
        {% endwith %}
        {% endfor %}
      </li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h4>{% trans "Members" %}</h4>
    <div class="tab-content paginate paginate-auto" id="search-content">
    {% include 'people/_profile_list_item.html' %}
    </div>
  </div>
  {% include 'search/_pagination.html' %}
</div>
{% endblock %}


{% block extra_script %}
  <script type="text/javascript">
  SEARCH_URL = '{% url 'api_dispatch_list' api_name='api' resource_name='profiles' %}'+ '?group='+ '{{ object.slug }}';
  </script>
  {% with include_spatial='false' %}
  {% include 'search/search_scripts.html' %}
  {% endwith %}
{% endblock extra_script %}

groups/templates/groups/group_invite_response.html
{% extends "groups/base.html" %}
{% load i18n %}

{% block body %}
<div class="onecol">

    <h2> {% trans "Members" %} </h2>
    <div id="assets"></div>

    <h2>{% trans "Membership Request" %}</h2>
    <p>You have been invited to join the group {{ object.title }}. Would you like to join?
    <form class="uniForm" method="POST" action="">
        {% csrf_token %}
        <button type="submit" value="decline" name="decline">{% trans "Don't Join" %}</button>
        <button type="submit" value="accept" name="accept">{% trans "Join Group" %}</button>
    </form>
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %} {% trans "Explore Groups" %} - {{ block.super }} {% endblock %}

{% block body_class %}groups explore{% endblock %}

{% block body %}
  <div class="page-header">
    {% if user.is_authenticated %}
    <a href="{% url "group_create" %}" class="btn btn-primary pull-right">{% trans "Create a New Group" %}</a>
    {% endif %}
    <h2>{% trans "Explore Groups" %}</h2>
  </div>

  <div class="btn-group pull-right" role="group" aria-label="sort">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-sort-alpha-asc fa-lg"></i>
        <i class="fa fa-angle-down fa-lg"></i>
      </button>
      <ul class="dropdown-menu" id="sort">
        <li><a data-value="-date" data-filter="order_by" class="selected" ng-click="single_choice_listener($event)">{% trans "Most recent" %}</a></li>
        <li><a data-value="date" data-filter="order_by" ng-click="single_choice_listener($event)">{% trans "Less recent" %}</a></li>
        <li><a data-value="title" data-filter="order_by" ng-click="single_choice_listener($event)">{% trans "A - Z" %}</a></li>
        <li><a data-value="-title" data-filter="order_by" ng-click="single_choice_listener($event)">{% trans "Z - A" %}</a></li>
        <li><a data-value="-popular_count" data-filter="order_by" ng-click="single_choice_listener($event)">{% trans "Most popular" %}</a></li>
      </ul>
    </div>
  </div>

<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="tab-content col-sm-12" id="search-content">
        {% include "groups/_group_list_item.html" %}
      </div>
    </div>
  </div>
</div>

{% include 'search/_pagination.html' %}
{% endblock %}

{% block extra_script %}
  <script type="text/javascript">
  SEARCH_URL = '{% url 'api_dispatch_list' api_name='api' resource_name='groups' %}'
  </script>
  {% with include_spatial='false' %}
  {% include 'search/search_scripts.html' %}
  {% endwith %}
{% endblock extra_script %}

groups/templates/groups/group_remove.html
{% extends "groups/group_base.html" %}
{% load i18n %}

{% block title %}{{ group.title }} — {{ block.super }}{% endblock %}
{% block body_class %}groups remove{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-8">
    <form action="{% url "group_remove" group.slug %}" method="POST">
      <h2>
        {% blocktrans with group.title as group_title %}
          Are you sure you want to remove the group: {{ group_title }}?
        {% endblocktrans %}
      </h2>
      {% csrf_token %}
      <input type="hidden" value="{{ group.slug }}" />
      <div class="form-actions">
        <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger" />
        <a href="{% url "group_detail" group.slug %}" class="btn btn-info">{% trans "No, don't remove it" %}</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

groups/templates/groups/group_remove_maps_data.html
{% extends "groups/group_base.html" %}
{% load i18n %}

{% block sidebar %}
<div class="col-md-2">
    <h2>{% trans "Remove Maps/Data from Group" %}</h2>
    <form method="POST" action="">
    {% csrf_token %}
    <ul>
    {{ map_form.as_ul }}
    </ul>
    <ul>
    {{ layer_form.as_ul }}
    </ul>
    <input type="submit" value="{% trans "Remove selected maps/data" %}" />
    </form>
</div>
{% endblock %}

groups/templates/groups/group_update.html
{% extends "groups/group_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block head_title %}{% trans "Create Group" %}{% endblock %}
{% block body_class %}groups update{% endblock %}

{% block body %}
     <div class="block">
        <div class="col-md-10">
          <h2 class="page-title">{% trans "Update Group" %}</h2>
          {% if errors %}
            <div id="errors">
              {% for error in errors %}
                <div>{{ error }}</div>
              {% endfor %}
            </div>
          {% endif %}
            <div>
                    <form class="uniForm" id="form" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            {{ form|as_bootstrap }}
            <div class="form_block">
                <input type="hidden" name="action" value="create" />
                <input type="submit" class="btn btn-primary" value="{% trans 'Update' %}"/>
            </div>
        </fieldset>
    </form>
            </div>
        </div>
    </div>
    
{% endblock %}